import assert from 'node:assert/strict';
import { useManualStore, migrateManualNavigation, type ManualConversation } from './manual-store';
import { useMissionStore } from './mission-store';
import { conversationActivity, type AgentActivity } from '@/components/manual/manual-activity';
import type { ManualAgent } from './manual-store';

const conversation: ManualConversation = { id: 'manual-a', workspaceId: 'project-a', title: 'Manual work', createdAt: '2026-09-08', agents: [] };
const store = useManualStore;
assert.equal(migrateManualNavigation({mode:'orchestrator'}).mode,'choose', 'Existing installations discover the new workspace home');
assert.deepEqual(migrateManualNavigation({activeByWorkspace:{project:'conversation'}}).activeByWorkspace,{project:'conversation'},'Navigation migration preserves saved conversation selection');
store.setState({ conversations: {'project-a': [conversation]}, activeByWorkspace: {}, agentByConversation: {}, surfaceByConversation: {}, drafts: {} });
store.getState().select(conversation);
store.getState().selectAgent('manual-a', 'agent-a');
store.getState().setDraft('agent-a', 'Keep this draft');
store.getState().setDraft('agent-b', 'Separate draft');
store.getState().setSurface('manual-a', 'code');
store.getState().setLayout('manual-a', 4);
store.getState().setLayout('manual-b', 2);
assert.equal(store.getState().layoutByConversation['manual-a'], 4, 'Terminal layouts are scoped to each conversation');
store.getState().setLayout('manual-b', 3);
assert.equal(store.getState().layoutByConversation['manual-b'], 1, 'Unsupported layouts fall back to focus');
store.getState().setMode('orchestrator');
store.getState().select(conversation);
assert.equal(store.getState().surfaceByConversation['manual-a'], 'code');
assert.equal(store.getState().agentByConversation['manual-a'], 'agent-a');
assert.equal(store.getState().drafts['agent-a'], 'Keep this draft');
assert.equal(store.getState().drafts['agent-b'], 'Separate draft');
const fetchMissionState = useMissionStore.getState().fetchMissionState;
useMissionStore.setState({ fetchMissionState: async () => undefined });
useMissionStore.getState().setActiveMission('mission-a', false);
assert.equal(store.getState().mode, 'manual', 'Background mission hydration preserves manual navigation');
useMissionStore.getState().setActiveMission('mission-a');
assert.equal(store.getState().mode, 'orchestrator', 'Explicit mission selection opens the orchestrator even for the same mission');
useMissionStore.setState({ fetchMissionState });

const oldFetch = globalThis.fetch;
let release: (response: Response) => void = () => undefined;
globalThis.fetch = (() => new Promise<Response>(resolve => { release = resolve; })) as typeof fetch;
const stale = store.getState().refresh('project-a');
globalThis.fetch = (async () => new Response(JSON.stringify({...conversation, id: 'manual-b'}), {status: 200, headers: {'Content-Type': 'application/json'}})) as typeof fetch;
await store.getState().create('project-a', 'New work', 'manual-b');
release(new Response('[]', {status: 200, headers: {'Content-Type': 'application/json'}}));
await stale;
assert.ok(store.getState().conversations['project-a'].some(c => c.id === 'manual-b'), 'Stale hydration cannot erase a newly created conversation');
globalThis.fetch = oldFetch;
const agents = ['a','b','c'].map(id => ({id,conversationId:'manual-a'} as ManualAgent));
store.setState({conversations:{'project-a':[{...conversation,agents}]}});
store.getState().moveAgent('manual-a','a','c');
assert.deepEqual(store.getState().orderByConversation['manual-a'],['b','c','a']);
store.getState().moveAgent('manual-a','a','b');
assert.deepEqual(store.getState().orderByConversation['manual-a'],['a','b','c']);
store.getState().hideAgent('a',true);
assert.equal(store.getState().conversations['project-a'][0].agents.length,3,'Closing a pane preserves agent history');
const now = Date.parse('2026-09-09T10:10:00Z');
const observed = (state: string, lifecycle: AgentActivity['lifecycle'] = 'open'): AgentActivity => ({state,lifecycle,checkedAt:now,at:'2026-09-09T10:08:00Z'});
assert.equal(conversationActivity([],{},now).kind,'empty');
assert.equal(conversationActivity(agents,{},now).kind,'unknown');
assert.equal(conversationActivity(agents,{a:observed('unknown','closed'),b:observed('unknown','closed'),c:observed('unknown','exited')},now).kind,'closed');
assert.equal(conversationActivity(agents,{a:observed('completed'),b:observed('completed'),c:observed('unknown')},now).kind,'open','Unknown activity never counts as finished');
assert.equal(conversationActivity(agents,{a:observed('completed'),b:observed('completed'),c:observed('completed')},now).text,'Turns finished 2m ago');
assert.equal(conversationActivity(agents,{a:observed('completed'),b:observed('working'),c:observed('completed')},now).kind,'working');
assert.equal(conversationActivity(agents,{a:observed('completed'),b:observed('attention'),c:observed('working')},now).kind,'attention');
console.log('Manual navigation, independent drafts and stale hydration regression tests passed.');
