import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { pathToFileURL } from 'node:url';
import { ManualProviderBridge, parseCodexManualTranscript } from './manual-provider-bridge';
import type { ManualAgent } from './manual-conversations';

const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'atris-manual-providers-'));
const agent: ManualAgent = {id:randomUUID(), conversationId:randomUUID(), providerSessionId:randomUUID(), name:'Test agent', catalogId:'test', runtimeType:'codex', model:'test-model', accountProfileId:'test', cwd:temporary, configDir:path.join(temporary,'profile'), sharedProfile:false, createdAt:new Date().toISOString()};
const bridge = new ManualProviderBridge(temporary);
const line = (type: string, payload: unknown, timestamp = '2026-09-08T00:00:00Z') => JSON.stringify({type,payload,timestamp});
const publicTranscript = [
  line('session_meta',{id:agent.providerSessionId}),
  line('response_item',{type:'message', role:'developer', content:[{type:'input_text',text:'Internal config'}]}),
  line('event_msg',{type:'user_message',message:'Hello'}),
  line('response_item',{type:'message',role:'user',content:[{type:'input_text',text:'Injected environment'}]}),
  line('response_item',{type:'message',role:'assistant',channel:'analysis',content:[{type:'output_text',text:'Private reasoning'}]}),
  line('response_item',{type:'message',role:'assistant',channel:'final',content:[{type:'output_text',text:'Visible response'}]}),
].join('\n');
try {
  const claude = {...agent,id:randomUUID(),runtimeType:'claude_code'};
  const claudeArgs = bridge.prepareClaude(claude, false);
  const settingsFile = claudeArgs[claudeArgs.indexOf('--settings')+1];
  assert.ok(fs.existsSync(settingsFile), 'Claude settings travel as a file, not shell-interpreted JSON');
  assert.equal(JSON.parse(fs.readFileSync(settingsFile,'utf8')).hooks.SessionStart[0].hooks[0].type,'command');
  assert.deepEqual(bridge.prepareClaude(claude,false),claudeArgs,'Repeated launch reuses immutable settings');
  const parsed = parseCodexManualTranscript(publicTranscript, agent.providerSessionId);
  assert.deepEqual(parsed.map(message => message.text), ['Hello','Visible response']);
  assert.deepEqual(parseCodexManualTranscript(publicTranscript.split('\n').slice(2).join('\n'), agent.providerSessionId).map(m=>m.id), parsed.map(m=>m.id), 'Message identity survives bounded history reads');
  const askedCodex = parseCodexManualTranscript(line('response_item',{type:'function_call',name:'request_user_input',call_id:'call_1',arguments:JSON.stringify({questions:[{header:'Publish',question:'Proceed?',options:[{label:'Yes',description:'Continue'}]}]})}),agent.providerSessionId);
  assert.equal(askedCodex[0].question?.questions[0]?.question,'Proceed?');
  const args = bridge.prepareCodex(agent);
  assert.ok(args.includes('--profile'));
  assert.ok(!args.some(arg => arg.includes('bypass')), 'Hook trust is never bypassed');
  const profileText = fs.readFileSync(path.join(agent.configDir, `atris-manual-${agent.id}.config.toml`), 'utf8');
  assert.ok(profileText.includes('command_windows = "powershell.exe'));
  const script = path.join(temporary,'manual-sessions',agent.id,'bind-session.cjs');
  const bindingFile = path.join(temporary,'manual-sessions',agent.id,'bindings.jsonl');
  const transcript = path.join(agent.configDir, `${agent.providerSessionId}.jsonl`);
  fs.writeFileSync(transcript, publicTranscript);
  const callHook = (sessionId: string, transcriptPath: string) => spawnSync(process.execPath,[script,bindingFile],{input:JSON.stringify({hook_event_name:'SessionStart',session_id:sessionId,transcript_path:transcriptPath}),encoding:'utf8'});
  const hookResult = callHook(agent.providerSessionId, transcript);
  assert.equal(hookResult.status,0,`Synthetic hook failed: ${hookResult.stderr || hookResult.error?.message}`);
  assert.equal(bridge.read(agent).bound,true);
  assert.equal(bridge.read(agent).messages.length,2);
  assert.deepEqual(bridge.prepareCodex(agent).slice(0,2),['resume',agent.providerSessionId]);
  assert.equal(callHook(randomUUID(),transcript).status,0);
  assert.equal(bridge.read(agent).messages.length,2,'Wrong session headers are rejected');
  const external = path.join(temporary,'outside-profile.jsonl'); fs.writeFileSync(external,publicTranscript);
  callHook(agent.providerSessionId,external);
  assert.equal(bridge.read(agent).messages.length,2,'Out-of-profile history paths cannot replace a binding');
  const activityAt = new Date(Date.now() + 1000).toISOString();
  fs.appendFileSync(bindingFile, JSON.stringify({sessionId:agent.providerSessionId,transcriptPath:transcript,event:'UserPromptSubmit',at:activityAt})+'\n');
  assert.deepEqual(bridge.activity(agent), {state:'working',at:activityAt});
  fs.appendFileSync(bindingFile, JSON.stringify({sessionId:agent.providerSessionId,transcriptPath:external,event:'Stop',at:new Date(Date.now()+2000).toISOString()})+'\n');
  assert.equal(bridge.activity(agent).state,'working','Foreign transcript cannot finish this agent');
  fs.appendFileSync(bindingFile, JSON.stringify({sessionId:agent.providerSessionId,transcriptPath:transcript,event:'Stop',at:new Date(Date.now()+3000).toISOString()})+'\n');
  assert.equal(bridge.activity(agent).state,'completed');
  assert.equal(bridge.activity({...agent,runtimeType:'antigravity'}).state,'unknown');

  // Optional local CLI schema smoke: no model, authentication, network or task is invoked.
  if (process.env.ATRIS_TEST_CODEX_EXECUTABLE) {
    const smoke = spawnSync(process.env.ATRIS_TEST_CODEX_EXECUTABLE,['--profile',`atris-manual-${agent.id}`,'mcp','list'],{env:{...process.env,CODEX_HOME:agent.configDir},encoding:'utf8',timeout:10000});
    assert.equal(smoke.status,0,`Installed Codex rejected the generated profile: ${smoke.stderr}`);
    console.log('Installed Codex accepted the generated layered hook profile.');
  }

  const openAgent = {...agent,id:randomUUID(),runtimeType:'opencode',model:'test/model',reasoning:'high'};
  const prepared = bridge.prepareOpenCode(openAgent);
  assert.ok(!prepared.args.includes('--variant'), 'TUI does not support run-only variant flag');
  assert.ok(bridge.prepareCodex({...agent,reasoning:'high'}).includes('model_reasoning_effort="high"'));
  assert.ok(!('OPENCODE_CONFIG_CONTENT' in prepared.env),'Inherited config values never cross the UI transport');
  const plugin = await import(prepared.env.ATRIS_MANUAL_OPENCODE_PLUGIN);
  const replies: unknown[] = [];
  const commands: unknown[] = [];
  let acceptMode = true;
  let failReply = false;
  const observer = await plugin.AtrisManualSession({directory:temporary,client:{_client:{post:async (value: unknown) => { replies.push(value); return failReply ? {error:{message:'Unavailable'}} : {data:true}; }},tui:{executeCommand:async (value: unknown) => { commands.push(value); return {data:acceptMode}; }}}});
  assert.deepEqual(bridge.autoApprove(openAgent),{available:true,enabled:false});
  assert.deepEqual(bridge.autoApprove({...openAgent,id:randomUUID()}),{available:false,enabled:false}, 'Permission mode belongs to this agent only');
  assert.throws(() => bridge.setAutoApprove(openAgent,'true'), /Invalid OpenCode/);
  const permission = async (status: 'ask'|'deny'|'allow') => {
    const output = {status};
    await observer['permission.ask']({sessionID:'ses_root'}, output);
    return output.status;
  };
  assert.equal(await permission('ask'),'ask','Permission requests still ask by default');
  bridge.setAutoApprove(openAgent,true);
  assert.throws(() => bridge.setAutoApprove(openAgent,false), /already changing/);
  await new Promise(resolve=>setTimeout(resolve,350));
  assert.deepEqual(bridge.autoApprove(openAgent),{available:true,enabled:true});
  assert.deepEqual(commands,[{body:{command:'permission.mode'}}], 'The native OpenCode TUI enters Auto mode');
  assert.equal(await permission('ask'),'ask','The plugin never overrides OpenCode permission rules');
  assert.equal(await permission('deny'),'deny','Explicit denials remain authoritative');
  bridge.setAutoApprove(openAgent,false);
  await new Promise(resolve=>setTimeout(resolve,350));
  assert.deepEqual(bridge.autoApprove(openAgent),{available:true,enabled:false});
  assert.equal(commands.length,2,'Disabling Auto toggles the native TUI back to normal');
  assert.equal(await permission('ask'),'ask','Disabling restores the normal permission flow');
  await observer.event({event:{type:'session.created',properties:{info:{id:'ses_root'}}}});
  await new Promise(resolve=>setTimeout(resolve,120));
  assert.equal(bridge.activity(openAgent).state,'ready');
  await observer.event({event:{type:'session.status',properties:{sessionID:'ses_root',status:{type:'busy'}}}});
  assert.equal(bridge.activity(openAgent).state,'working');
  await observer.event({event:{type:'session.idle',properties:{sessionID:'ses_child'}}});
  assert.equal(bridge.activity(openAgent).state,'working','Child completion cannot notify for the root agent');
  await observer.event({event:{type:'session.idle',properties:{sessionID:'ses_root'}}});
  assert.equal(bridge.activity(openAgent).state,'completed');
  acceptMode = false;
  bridge.setAutoApprove(openAgent,true);
  await new Promise(resolve=>setTimeout(resolve,350));
  assert.equal(bridge.autoApprove(openAgent).enabled,false,'Rejected TUI command does not claim Auto mode is active');
  assert.match(bridge.autoApprove(openAgent).error || '',/Could not change/);
  acceptMode = true;
  bridge.setAutoApprove(openAgent,true);
  await new Promise(resolve=>setTimeout(resolve,350));
  assert.equal(bridge.autoApprove(openAgent).enabled,true);
  assert.equal(await permission('ask'),'ask','Auto never changes plugin decisions for the root session');
  assert.equal((await observer['permission.ask']({sessionID:'ses_child'},{status:'ask'})),undefined,'Child sessions are not intercepted');
  const rootMessage = {message:{model:{providerID:'old',modelID:'previous',variant:'low'}},parts:[]};
  await observer['chat.message']({sessionID:'ses_root'},rootMessage);
  assert.deepEqual(rootMessage.message.model,{providerID:'test',modelID:'model',variant:'high'},'Selected model and reasoning reach the executable user message even when hook input has no model');
  bridge.updateOpenCodeRoute({...openAgent,model:'other/new',reasoning:'low'});
  const updatedMessage = {message:{model:{providerID:'test',modelID:'model',variant:'high'}},parts:[]};
  await observer['chat.message']({sessionID:'ses_root',model:{providerID:'test',modelID:'model'}},updatedMessage);
  assert.deepEqual(updatedMessage.message.model,{providerID:'other',modelID:'new',variant:'low'},'Live model/reasoning update affects the next prompt without reloading the plugin');
  bridge.updateOpenCodeRoute({...openAgent,model:'other/new',reasoning:'none'});
  const noReasoning = {message:{model:{providerID:'test',modelID:'model',variant:'high'}},parts:[]};
  await observer['chat.message']({sessionID:'ses_root'},noReasoning);
  assert.deepEqual(noReasoning.message.model,{providerID:'other',modelID:'new',variant:'none'},'None selects the explicit non-reasoning variant');
  const childMessage = {message:{model:{providerID:'child',modelID:'own'}},parts:[]};
  await observer['chat.message']({sessionID:'ses_child',model:{providerID:'test',modelID:'model'}},childMessage);
  assert.deepEqual(childMessage.message.model,{providerID:'child',modelID:'own'},'Independent subagent model is not overwritten');
  await observer.event({event:{type:'message.updated',properties:{info:{id:'msg_one',sessionID:'ses_root',role:'assistant'}}}});
  await observer.event({event:{type:'message.part.updated',properties:{part:{id:'part_one',messageID:'msg_one',sessionID:'ses_root',type:'text',text:'Live response'}}}});
  await observer.event({event:{type:'session.created',properties:{info:{id:'ses_child',parentID:'ses_root'}}}});
  await observer.event({event:{type:'message.part.updated',properties:{part:{id:'foreign',messageID:'msg_one',sessionID:'ses_child',type:'text',text:'Wrong agent'}}}});
  const prompt = {id:'que_test',sessionID:'ses_root',questions:[{header:'Publish',question:'Continue?',options:[{label:'Yes'},{label:'No'}]}]};
  await observer.event({event:{type:'question.asked',properties:prompt}});
  assert.equal(bridge.activity(openAgent).state,'attention');
  await observer.event({event:{type:'session.idle',properties:{sessionID:'ses_root'}}});
  assert.equal(bridge.activity(openAgent).state,'attention','Idle while waiting for a question is not completion');
  await new Promise(resolve=>setTimeout(resolve,160));
  const history = bridge.read(openAgent);
  assert.equal(history.bound,true);
  assert.deepEqual(history.messages.map(m=>m.text),['Live response']);
  assert.equal(bridge.pendingQuestions(openAgent)[0]?.questions[0]?.question,'Continue?');
  assert.deepEqual(bridge.pendingQuestions({...openAgent,id:randomUUID()}),[], 'A different agent never sees this question');
  assert.throws(() => bridge.replyQuestion(openAgent,'wrong',[['Yes']]), /no longer pending/);
  assert.throws(() => bridge.replyQuestion(openAgent,prompt.id,[]), /Select an answer/);
  bridge.replyQuestion(openAgent,prompt.id,[['Yes']]);
  for (let attempt = 0; attempt < 20 && !replies.length; attempt++) await new Promise(resolve=>setTimeout(resolve,100));
  assert.deepEqual(replies,[{url:'/question/{requestID}/reply',path:{requestID:prompt.id},query:{directory:temporary},body:{answers:[['Yes']]},headers:{'Content-Type':'application/json'}}]);
  assert.deepEqual(bridge.pendingQuestions(openAgent),[]);
  const retryPrompt = {...prompt,id:'que_retry'};
  await observer.event({event:{type:'question.asked',properties:retryPrompt}});
  failReply = true;
  bridge.replyQuestion(openAgent,retryPrompt.id,[['No']]);
  await new Promise(resolve=>setTimeout(resolve,380));
  assert.match(bridge.pendingQuestions(openAgent)[0]?.deliveryError || '', /Retry or answer in Code/);
  failReply = false;
  bridge.replyQuestion(openAgent,retryPrompt.id,[['Yes']]);
  await new Promise(resolve=>setTimeout(resolve,380));
  assert.deepEqual(bridge.pendingQuestions(openAgent),[], 'A rejected delivery can be retried without restarting the agent');
  const answeredInCode = {...prompt,id:'que_code'};
  await observer.event({event:{type:'question.asked',properties:answeredInCode}});
  bridge.replyQuestion(openAgent,answeredInCode.id,[['Yes']]);
  await observer.event({event:{type:'question.replied',properties:{sessionID:'ses_root',requestID:answeredInCode.id}}});
  assert.deepEqual(bridge.pendingQuestions(openAgent),[], 'Answering in Code clears the queued Chat answer');
  const nextPrompt = {...prompt,id:'que_next'};
  await observer.event({event:{type:'question.asked',properties:nextPrompt}});
  assert.doesNotThrow(() => bridge.replyQuestion(openAgent,nextPrompt.id,[['No']]));
  await new Promise(resolve=>setTimeout(resolve,380));
  assert.deepEqual(bridge.pendingQuestions(openAgent),[]);
  await observer.event({event:{type:'question.replied',properties:{requestID:prompt.id}}});
  assert.equal(bridge.activity(openAgent).state,'working');
  await observer.event({event:{type:'session.idle',properties:{sessionID:'ses_root'}}});
  assert.equal(bridge.activity(openAgent).state,'completed');
  assert.equal(bridge.activity({...openAgent,id:randomUUID()}).state,'unknown');
  assert.deepEqual(bridge.prepareOpenCode(openAgent).args.slice(0,2),['--session','ses_root']);
  assert.equal(bridge.activity(openAgent).state,'unknown','Restart does not reuse a previous turn notification');
  assert.deepEqual(bridge.autoApprove(openAgent),{available:false,enabled:false}, 'A restarted TUI never inherits a stale permission indicator');
  assert.equal(pathToFileURL(script).protocol,'file:');
  console.log('Codex hook binding, transcript isolation, resume and OpenCode plugin regression tests passed.');
} finally { fs.rmSync(temporary,{recursive:true,force:true}); }
