import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { ManualProviderBridge } from './manual-provider-bridge';
import type { ManualAgent } from './manual-conversations';

const temporary = fs.mkdtempSync(path.join(os.tmpdir(),'atris-opencode-tui-'));
const agent: ManualAgent = {id:randomUUID(),conversationId:randomUUID(),providerSessionId:randomUUID(),name:'Test',catalogId:'test',runtimeType:'opencode',model:'openai/test',reasoning:'high',accountProfileId:'test',cwd:temporary,configDir:temporary,sharedProfile:false,createdAt:new Date().toISOString()};
const bridge = new ManualProviderBridge(temporary);
const prepared = bridge.prepareOpenCode(agent);
const root = path.dirname(prepared.env.ATRIS_MANUAL_OPENCODE_TUI_CONFIG);
const read = (name: string) => JSON.parse(fs.readFileSync(path.join(root,name),'utf8'));
const config = JSON.parse(fs.readFileSync(prepared.env.ATRIS_MANUAL_OPENCODE_TUI_CONFIG,'utf8').split('\n').slice(1).join('\n'));
const plugin = await import(config.plugin[0][0]);
const sleep = (ms: number) => new Promise(resolve=>setTimeout(resolve,ms));
const wait = async (predicate:()=>boolean) => { for(let i=0;i<60;i++){if(predicate())return;await sleep(50);}assert.ok(predicate(),'TUI selection was not confirmed'); };
let dispose:()=>void = ()=>{};
try {
  fs.mkdirSync(path.join(root,'mock-state'),{recursive:true});
  let busy = true, dialog = false, current = 'default', automatic = false;
  let currentModel = agent.model;
  let messages: Array<{id:string;role:string;model:{providerID:string;modelID:string;variant:string}}> = [];
  const navigation: string[] = [];
  const calls: string[] = [];
  const choices = ['default','none','low','high'];
  const api = {state:{ready:true,path:{state:path.join(root,'mock-state')},provider:[{id:'openai',models:{test:{variants:{none:{},low:{},high:{}}},other:{variants:{none:{},low:{},high:{}}}}}],session:{get:()=>({}),status:()=>({type:busy?'busy':'idle'}),messages:()=>messages}},ui:{dialog:{get open(){return dialog;}}},route:{current:{name:'session',params:{sessionID:'ses_test'}},register:()=>()=>{},navigate:(name:string)=>{navigation.push(name);if(name==='session'){const last=messages.at(-1)!;currentModel=last.model.providerID+'/'+last.model.modelID;current=last.model.variant;}}},keymap:{getCommandEntries:()=>[{command:{name:'permission.mode',title:automatic?'Disable auto-approve permissions':'Enable auto-approve permissions'}}],dispatchCommand:async(command:string)=>{calls.push(command);if(command==='permission.mode'){automatic=!automatic;return;}assert.equal(command,'variant.cycle');current=choices[(choices.indexOf(current)+1)%choices.length];fs.writeFileSync(path.join(root,'mock-state/model.json'),JSON.stringify({variant:{[currentModel]:current}}));}},lifecycle:{onDispose:(fn:()=>void)=>{dispose=fn;}}};
  await plugin.tui(api);
  await sleep(350);
  assert.equal(calls.length,0,'A running turn is never given a different reasoning variant mid-execution');
  busy=false;dialog=true;
  await sleep(350);
  assert.equal(calls.length,0,'An existing Code dialog is never replaced');
  dialog=false;
  await wait(()=>fs.existsSync(path.join(root,'opencode-route-state.json'))&&read('opencode-route-state.json').applied);
  assert.equal(current,'high','Initial selected reasoning reaches the real TUI command path');
  bridge.updateOpenCodeRoute({...agent,reasoning:'low'});
  const lowRevision = read('opencode-route.json').id;
  await wait(()=>read('opencode-route-state.json').id===lowRevision);
  assert.equal(current,'low','An immediate same-model reasoning change updates Code without a prompt or restart');
  bridge.updateOpenCodeRoute({...agent,reasoning:'none'});
  const noneRevision = read('opencode-route.json').id;
  await wait(()=>read('opencode-route-state.json').id===noneRevision);
  assert.equal(current,'none','None is an explicit variant, not the provider default');
  current='high';
  fs.writeFileSync(path.join(root,'mock-state/model.json'),JSON.stringify({variant:{[agent.model]:current}}));
  await wait(()=>current==='none'&&read('opencode-route-state.json').applied);
  assert.equal(current,'none','Native session restoration cannot leave a previously confirmed reasoning route stale');
  messages=[{id:'msg_old',role:'user',model:{providerID:'openai',modelID:'test',variant:'none'}}];
  const beforeSwitch=calls.length;
  bridge.updateOpenCodeRoute({...agent,model:'openai/other',reasoning:'high'});
  const modelRevision=read('opencode-route.json').id;
  await wait(()=>read('opencode-route-state.json').id===modelRevision);
  await sleep(350);
  assert.equal(calls.length,beforeSwitch,'A different model does not cycle the previous model or fake a user submission');
  assert.equal(bridge.openCodeRouteStatus(agent)?.pending,true);
  messages.push({id:'msg_actual',role:'user',model:{providerID:'openai',modelID:'other',variant:'high'}});
  await wait(()=>read('opencode-route-state.json').applied===true);
  assert.deepEqual(navigation,['atris-route-sync','session']);
  assert.equal(currentModel,'openai/other','The next actual message rehydrates the CLI model');
  assert.equal(current,'high');
  dialog=true;
  bridge.setAutoApprove(agent,true);
  await sleep(350);
  assert.equal(automatic,false,'Auto does not dismiss an existing Code dialog');
  assert.equal(fs.existsSync(path.join(root,'opencode-auto-request.json')),true,'The mode request waits for that dialog to close');
  dialog=false;
  await wait(()=>bridge.autoApprove(agent).enabled);
  automatic=false;
  await wait(()=>!bridge.autoApprove(agent).enabled);
  assert.equal(calls.filter(command=>command==='permission.mode').length,1,'A Code-side mode change does not cause an inverse toggle');
  dispose();
  assert.equal(bridge.autoApprove(agent).available,false,'A disposed TUI never advertises working live controls');

  if(process.env.ATRIS_TEST_OPENCODE_EXECUTABLE){
    const isolated=path.join(root,'isolated');fs.mkdirSync(isolated,{recursive:true});
    // No real provider or credentials: this fixture never submits a model prompt.
    fs.writeFileSync(path.join(isolated,'opencode.json'),JSON.stringify({enabled_providers:['openai'],autoupdate:false,provider:{openai:{options:{apiKey:'fixture-only',baseURL:'http://127.0.0.1:1/v1'},models:{test:{name:'Atris test',reasoning:true,limit:{context:32768,output:4096},variants:{none:{reasoningEffort:'none'},low:{reasoningEffort:'low'},high:{reasoningEffort:'high'}}}}}}}));
    const fixture=path.join(root,'native-fixture.json');
    fs.writeFileSync(fixture,JSON.stringify({...prepared,id:agent.id,executable:process.env.ATRIS_TEST_OPENCODE_EXECUTABLE,cwd:isolated,root,env:{...prepared.env,XDG_CONFIG_HOME:path.join(isolated,'config'),XDG_DATA_HOME:path.join(isolated,'data')}}));
    const cargo=spawnSync('cargo',['test','--lib','installed_opencode_tui_controls','--','--nocapture'],{cwd:fileURLToPath(new URL('../../../apps/desktop/src-tauri',import.meta.url)),env:{...process.env,ATRIS_TEST_OPENCODE_FIXTURE:fixture},encoding:'utf8',timeout:120000});
    assert.equal(cargo.status,0,cargo.stdout+'\n'+cargo.stderr);
    console.log(cargo.stdout);
  }
  console.log('OpenCode TUI reasoning, busy/dialog fencing, Auto confirmation and Code-side synchronization passed.');
}finally{dispose();fs.rmSync(temporary,{recursive:true,force:true,maxRetries:10,retryDelay:100});}
