import type { TeamTemplate } from '@atris-agent-code/domain';

export const DEFAULT_TEAM_TEMPLATE_ID = 'default-core-dev-team';
export const CORE_DEV_TEAM_NAME = 'Core Dev Team';

const CORE_DEV_TEAM_KEY = CORE_DEV_TEAM_NAME.toLowerCase();
const GENERATED_CUSTOM_SECURITY_TEAM_PATTERN = /^custom\s+security\s+team\s+\d{8,}$/i;

export function normalizeTeamTemplateName(name: string): string {
  return name.trim().replace(/\s+/g, ' ');
}

export function isCoreDevTeam(template: TeamTemplate): boolean {
  return template.id === DEFAULT_TEAM_TEMPLATE_ID
    || normalizeTeamTemplateName(template.name).toLowerCase() === CORE_DEV_TEAM_KEY;
}

/**
 * These names are generated by the API test fixture. They are hidden from the
 * desktop catalog, but never deleted or changed on the server.
 */
export function isGeneratedTeamTemplate(template: TeamTemplate): boolean {
  return GENERATED_CUSTOM_SECURITY_TEAM_PATTERN.test(normalizeTeamTemplateName(template.name));
}

function isValidTeamTemplate(template: TeamTemplate | null | undefined): template is TeamTemplate {
  return Boolean(
    template
      && typeof template.id === 'string'
      && template.id.trim()
      && typeof template.name === 'string'
      && template.name.trim(),
  );
}

function templateNameKey(template: TeamTemplate): string {
  return normalizeTeamTemplateName(template.name).toLowerCase();
}

function preferenceScore(template: TeamTemplate): number {
  return (isCoreDevTeam(template) ? 4 : 0)
    + (template.isDefault ? 2 : 0)
    + (isGeneratedTeamTemplate(template) ? -4 : 0);
}

function preferredTemplate(candidate: TeamTemplate, current: TeamTemplate): TeamTemplate {
  const scoreDifference = preferenceScore(candidate) - preferenceScore(current);
  if (scoreDifference !== 0) return scoreDifference > 0 ? candidate : current;

  const createdAtDifference = (candidate.createdAt || '').localeCompare(current.createdAt || '');
  if (createdAtDifference !== 0) return createdAtDifference < 0 ? candidate : current;
  return candidate.id.localeCompare(current.id) < 0 ? candidate : current;
}

function compareForDisplay(left: TeamTemplate, right: TeamTemplate): number {
  const leftCore = isCoreDevTeam(left);
  const rightCore = isCoreDevTeam(right);
  if (leftCore !== rightCore) return leftCore ? -1 : 1;

  if (left.isDefault !== right.isDefault) return left.isDefault ? -1 : 1;

  const nameDifference = normalizeTeamTemplateName(left.name).localeCompare(
    normalizeTeamTemplateName(right.name),
    undefined,
    { numeric: true, sensitivity: 'base' },
  );
  if (nameDifference !== 0) return nameDifference;
  return left.id.localeCompare(right.id);
}

/**
 * Returns a stable, compact presentation catalog without mutating server data.
 * Duplicate IDs and duplicate names collapse to the most authoritative row;
 * real custom names remain visible.
 */
export function normalizeTeamTemplates(templates: readonly TeamTemplate[]): TeamTemplate[] {
  const byId = new Map<string, TeamTemplate>();

  for (const template of templates) {
    if (!isValidTeamTemplate(template) || isGeneratedTeamTemplate(template)) continue;
    const normalized = {
      ...template,
      id: template.id.trim(),
      name: normalizeTeamTemplateName(template.name),
    };
    const current = byId.get(normalized.id);
    byId.set(normalized.id, current ? preferredTemplate(normalized, current) : normalized);
  }

  const byName = new Map<string, TeamTemplate>();
  for (const template of byId.values()) {
    const key = templateNameKey(template);
    const current = byName.get(key);
    byName.set(key, current ? preferredTemplate(template, current) : template);
  }

  return Array.from(byName.values()).sort(compareForDisplay);
}

export function getDefaultTeamTemplate(templates: readonly TeamTemplate[]): TeamTemplate | undefined {
  const normalized = normalizeTeamTemplates(templates);
  return normalized.find((template) => template.isDefault)
    || normalized.find((template) => template.id === DEFAULT_TEAM_TEMPLATE_ID)
    || normalized.find(isCoreDevTeam)
    || normalized[0];
}

/**
 * Reconciles persisted IDs after a template is deleted or hidden as a known
 * generated fixture. The returned ID is always present in the visible catalog,
 * unless the service returned no templates, in which case the stable default
 * ID is used as the safe server seed fallback.
 */
export function reconcileTeamTemplateId(
  templates: readonly TeamTemplate[],
  selectedId: string | null | undefined,
): string {
  const normalized = normalizeTeamTemplates(templates);
  const selected = selectedId?.trim();
  if (selected && normalized.some((template) => template.id === selected)) return selected;
  return getDefaultTeamTemplate(normalized)?.id || DEFAULT_TEAM_TEMPLATE_ID;
}

export function normalizeStoredTeamTemplateId(templateId: string | null | undefined): string {
  const normalized = templateId?.trim();
  return !normalized || normalized.toLowerCase() === CORE_DEV_TEAM_KEY
    ? DEFAULT_TEAM_TEMPLATE_ID
    : normalized;
}
