import { useEffect, useState } from 'react';
import { Brain, Link2, Plus, Loader2, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { MemoryTab } from '@/components/inspector/memory-tab';
import { apiRequest } from '@/lib/api-client';
import type { MemoryNode } from '@/stores/memory-store';
import type { ManualAgent, ManualConversation, ManualMessage } from '@/stores/manual-store';

export function ManualMemory({conversation,agent,message,onClose}:{conversation:ManualConversation;agent?:ManualAgent;message?:ManualMessage;onClose:()=>void}) {
  const [view,setView]=useState<'notes'|'references'|'project'>('notes');
  const [nodes,setNodes]=useState<MemoryNode[]>([]),[loading,setLoading]=useState(true),[pending,setPending]=useState(false),[error,setError]=useState('');
  const [editing,setEditing]=useState(!!message),[title,setTitle]=useState(message?`From ${agent?.name||'conversation'}`:''),[text,setText]=useState(message?.text||''),[url,setUrl]=useState('');
  const [sourceId,setSourceId]=useState(message?.id);
  const [refresh,setRefresh]=useState(0);
  const endpoint=`/manual/conversations/${conversation.id}/memory`;
  useEffect(()=>{let disposed=false;setLoading(true);setNodes([]);setError('');void apiRequest<{nodes:MemoryNode[]}>(endpoint).then(result=>{if(!disposed)setNodes(result.nodes);}).catch(cause=>{if(!disposed)setError(String(cause));}).finally(()=>{if(!disposed)setLoading(false);});return()=>{disposed=true;};},[endpoint,refresh]);
  const save=async()=>{
    if(pending||!title.trim()||!text.trim())return;setPending(true);setError('');
    try{const node=await apiRequest<MemoryNode>(endpoint,{method:'POST',body:JSON.stringify({title,summary:text.slice(0,4000),body:text,agentId:agent?.id,sourceId,type:view==='references'?'external_source':'decision',url:view==='references'?url:undefined})});setNodes(previous=>[node,...previous]);setEditing(false);setTitle('');setText('');setUrl('');setSourceId(undefined);}
    catch(cause){setError(String(cause));}finally{setPending(false);}
  };
  const filtered=nodes.filter(node=>view==='references'?node.type==='external_source':node.type!=='external_source');
  return <Dialog open onOpenChange={open=>{if(!open&&!pending)onClose();}}><DialogContent className="flex h-[calc(100vh-3rem)] w-[calc(100vw-3rem)] max-w-none flex-col overflow-hidden rounded-2xl p-0 sm:max-w-none"><DialogHeader className="shrink-0 border-b border-border px-6 py-5"><DialogTitle>Memory & references</DialogTitle><DialogDescription>{conversation.title} · Saved context with conversation and agent provenance</DialogDescription></DialogHeader>
    <div className="flex shrink-0 items-center justify-between gap-2 border-b border-border px-5 py-3"><div className="flex gap-1">{(['notes','references','project'] as const).map(tab=><Button key={tab} type="button" size="sm" variant={view===tab?'secondary':'ghost'} onClick={()=>{setView(tab);setEditing(false);}}>{tab==='notes'?'Conversation memory':tab==='references'?'References':'Project memory'}</Button>)}</div>{view!=='project'&&<div className="flex gap-1"><Button type="button" variant="ghost" size="icon" aria-label="Refresh manual memory" onClick={()=>setRefresh(n=>n+1)}><RefreshCw className="h-4 w-4"/></Button><Button type="button" size="sm" onClick={()=>{setTitle('');setText('');setUrl('');setSourceId(undefined);setEditing(true);}}><Plus className="mr-1 h-3.5 w-3.5"/>Add {view==='references'?'reference':'note'}</Button></div>}</div>
    {view==='project'?<div className="min-h-0 flex-1 overflow-auto"><MemoryTab/></div>:<div className="min-h-0 flex-1 overflow-auto px-6 py-5"><div className="mx-auto max-w-4xl">
      <p className="mb-5 text-xs leading-5 text-muted-foreground">Stored in this project’s durable memory, scoped to this manual conversation. Explicit user decisions and standing constraints are captured automatically from connected Chat history. Routine messages and unverified assistant claims are skipped. They are not silently injected into other agents.</p>
      {error&&<p role="alert" className="mb-3 text-sm text-destructive">{error}</p>}
      {editing&&<form className="mb-5 space-y-3 rounded-xl border border-border bg-background p-4" onSubmit={event=>{event.preventDefault();void save();}}><label className="block text-xs font-medium">Title<Input className="mt-1" value={title} maxLength={240} onChange={event=>setTitle(event.target.value)} required/></label>{view==='references'&&<label className="block text-xs font-medium">Reference URL<Input className="mt-1" type="url" value={url} maxLength={2000} onChange={event=>setUrl(event.target.value)} placeholder="https://…" required/></label>}<label className="block text-xs font-medium">{view==='references'?'Why this source matters':'Memory content'}<textarea aria-label="Memory content" className="mt-1 min-h-32 w-full rounded-lg border border-input bg-background p-3 text-sm" value={text} maxLength={24000} onChange={event=>setText(event.target.value)} required/></label><div className="flex items-center justify-between gap-2"><span className="text-xs text-muted-foreground">Source: {agent?.name||'Conversation'}{sourceId?' · selected message':''}</span><div className="flex gap-2"><Button type="button" variant="ghost" disabled={pending} onClick={()=>setEditing(false)}>Cancel</Button><Button type="submit" disabled={pending}>{pending?<Loader2 className="h-4 w-4 animate-spin"/>:'Save to memory'}</Button></div></div></form>}
      {loading?<p className="flex gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin"/>Loading memory…</p>:!filtered.length?<div className="rounded-xl border border-dashed border-border p-8 text-center"><Brain className="mx-auto mb-3 h-7 w-7 text-muted-foreground"/><h3 className="text-sm font-medium">No {view==='references'?'references':'saved notes'} yet</h3><p className="mt-2 text-xs text-muted-foreground">Important user decisions appear here automatically. You can also add a note or reference.</p></div>:<div className="space-y-3">{filtered.map(node=><article key={node.id} className="rounded-xl border border-border bg-background p-4"><div className="flex items-start gap-3">{node.type==='external_source'?<Link2 className="mt-0.5 h-4 w-4 shrink-0 text-primary"/>:<Brain className="mt-0.5 h-4 w-4 shrink-0 text-primary"/>}<div className="min-w-0 flex-1"><h3 className="text-sm font-medium">{node.title}</h3><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-muted-foreground">{node.body||node.summary}</p><div className="mt-3 flex flex-wrap gap-3 text-[11px] text-muted-foreground"><span>{new Date(node.createdAt).toLocaleString()}</span><span>{conversation.agents.find(item=>item.id===node.provenance?.[0]?.manualAgentId)?.name||'Conversation'}</span><span className="select-all">Record: {node.id}</span></div>{node.provenance?.filter(source=>source.url).map((source,index)=><p key={index} className="mt-2 break-all text-xs text-primary select-all">{source.url}</p>)}</div></div></article>)}</div>}
    </div></div>}
  </DialogContent></Dialog>;
}
